/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    icon: Icon;
    posts: Post;
    'tech-posts': TechPost;
    tags: Tag;
    topics: Topic;
    users: User;
    program: Program;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface Icon {
  id: string;
  name: string;
  value: string;
}
export interface Post {
  id: string;
  title: string;
  slug?: string | null;
  author?: (string | null) | User;
  publishedDate?: string | null;
  tags?: (string | Tag)[] | null;
  content: {
    [k: string]: unknown;
  }[];
  accordions?:
    | {
        accordionheader: string;
        accordionItems?:
          | {
              accordionitemheader?: string | null;
              accordionitemcontent: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  name: string;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Tag {
  id: string;
  name: string;
}
export interface TechPost {
  id: string;
  title: string;
  slug?: string | null;
  author?: (string | null) | User;
  publishedDate?: string | null;
  tags?: (string | Tag)[] | null;
  content: {
    [k: string]: unknown;
  }[];
  accordions?:
    | {
        accordionheader: string;
        accordionItems?:
          | {
              accordionitemheader?: string | null;
              accordionitemcontent: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
export interface Topic {
  id: string;
  title: string;
  slug?: string | null;
  icon?: (string | null) | Icon;
  tags: (string | Tag)[];
  content: {
    [k: string]: unknown;
  }[];
  accordions?:
    | {
        accordionheader: string;
        accordionItems?:
          | {
              accordionitemheader?: string | null;
              accordionitemcontent: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
export interface Program {
  id: string;
  slug?: string | null;
  title: string;
  passcode: string;
  content?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  accordions?:
    | {
        accordionheader: string;
        accordionItems?:
          | {
              accordionitemheader?: string | null;
              accordionitemcontent: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}